export interface TeamRanking {
  rank: number;
  nation: string;
  points: number;
}

export interface CollegeTeamRanking {
  rank: number;
  team: string;
  conference?: string;
  record?: string;
}

const COUNTRY_FLAGS: Record<string, string> = {
  "Mexico": "🇲🇽",
  "USA": "🇺🇸",
  "Great Britain": "🇬🇧",
  "Canada": "🇨🇦",
  "Japan": "🇯🇵",
  "Austria": "🇦🇹",
  "Spain": "🇪🇸",
  "Italy": "🇮🇹",
  "Germany": "🇩🇪",
  "Australia": "🇦🇺",
  "France": "🇫🇷",
  "Panama": "🇵🇦",
  "New Zealand": "🇳🇿",
  "Switzerland": "🇨🇭",
  "Brazil": "🇧🇷",
  "Czechia": "🇨🇿",
  "Finland": "🇫🇮",
  "Israel": "🇮🇱",
  "China": "🇨🇳",
  "Denmark": "🇩🇰",
  "Ireland": "🇮🇪",
  "Sweden": "🇸🇪",
  "Korea": "🇰🇷",
  "Malaysia": "🇲🇾",
  "Poland": "🇵🇱",
  "Philippines": "🇵🇭",
  "Indonesia": "🇮🇩",
  "Ukraine": "🇺🇦",
  "Nigeria": "🇳🇬",
  "American Samoa": "🇦🇸",
  "Thailand": "🇹🇭",
  "Morocco": "🇲🇦",
  "Slovenia": "🇸🇮",
  "Turkiye": "🇹🇷",
  "India": "🇮🇳",
  "Egypt": "🇪🇬",
  "Colombia": "🇨🇴",
  "Guatemala": "🇬🇹",
  "Norway": "🇳🇴",
  "Jordan": "🇯🇴",
  "Argentina": "🇦🇷",
  "Jamaica": "🇯🇲",
  "Hong Kong, China": "🇭🇰",
  "Netherlands": "🇳🇱",
  "Chile": "🇨🇱",
  "Kuwait": "🇰🇼",
  "Singapore": "🇸🇬",
  "Georgia": "🇬🇪",
  "Cameroon": "🇨🇲",
  "Tunisia": "🇹🇳",
  "Hungary": "🇭🇺",
  "Croatia": "🇭🇷",
  "Portugal": "🇵🇹",
  "Belgium": "🇧🇪",
  "Slovakia": "🇸🇰",
  "South Africa": "🇿🇦",
  "El Salvador": "🇸🇻",
  "Senegal": "🇸🇳",
  "Uganda": "🇺🇬",
  "Serbia": "🇷🇸",
};

export function getFlag(nation: string): string {
  return COUNTRY_FLAGS[nation] ?? "🏳️";
}

// Source: IFAF World Rankings — americanfootball.sport/ifaf-world-rankings/
// Last updated: 2025
export const WOMENS_WORLD_RANKINGS: TeamRanking[] = [
  { rank: 1,  nation: "Mexico",          points: 10987 },
  { rank: 2,  nation: "USA",             points: 10817 },
  { rank: 3,  nation: "Great Britain",   points: 8879  },
  { rank: 4,  nation: "Canada",          points: 8870  },
  { rank: 5,  nation: "Japan",           points: 8643  },
  { rank: 6,  nation: "Austria",         points: 8575  },
  { rank: 7,  nation: "Spain",           points: 6619  },
  { rank: 8,  nation: "Italy",           points: 6606  },
  { rank: 9,  nation: "Germany",         points: 6000  },
  { rank: 10, nation: "Australia",       points: 5818  },
  { rank: 11, nation: "France",          points: 5813  },
  { rank: 12, nation: "Panama",          points: 5755  },
  { rank: 13, nation: "New Zealand",     points: 5143  },
  { rank: 14, nation: "Switzerland",     points: 5138  },
  { rank: 15, nation: "Brazil",          points: 5093  },
  { rank: 16, nation: "Czechia",         points: 4907  },
  { rank: 17, nation: "Finland",         points: 4662  },
  { rank: 18, nation: "Israel",          points: 4462  },
  { rank: 18, nation: "China",           points: 4462  },
  { rank: 20, nation: "Denmark",         points: 4396  },
  { rank: 21, nation: "Ireland",         points: 4368  },
  { rank: 22, nation: "Sweden",          points: 4355  },
  { rank: 23, nation: "Korea",           points: 4136  },
  { rank: 24, nation: "Malaysia",        points: 3508  },
  { rank: 25, nation: "Poland",          points: 3050  },
  { rank: 26, nation: "Philippines",     points: 2980  },
  { rank: 27, nation: "Indonesia",       points: 2967  },
  { rank: 28, nation: "Ukraine",         points: 2942  },
  { rank: 29, nation: "Nigeria",         points: 2833  },
  { rank: 30, nation: "American Samoa",  points: 2800  },
  { rank: 31, nation: "Thailand",        points: 2751  },
  { rank: 32, nation: "Morocco",         points: 2500  },
  { rank: 33, nation: "Slovenia",        points: 2333  },
  { rank: 34, nation: "Turkiye",         points: 2283  },
  { rank: 35, nation: "India",           points: 2280  },
  { rank: 36, nation: "Egypt",           points: 2167  },
  { rank: 37, nation: "Colombia",        points: 2160  },
  { rank: 38, nation: "Guatemala",       points: 2125  },
  { rank: 39, nation: "Norway",          points: 2100  },
  { rank: 40, nation: "Jordan",          points: 2017  },
  { rank: 41, nation: "Argentina",       points: 1960  },
  { rank: 42, nation: "Jamaica",         points: 1920  },
  { rank: 42, nation: "Hong Kong, China",points: 1920  },
  { rank: 44, nation: "Netherlands",     points: 1817  },
  { rank: 45, nation: "Chile",           points: 642   },
];

export const MENS_WORLD_RANKINGS: TeamRanking[] = [
  { rank: 1,  nation: "USA",             points: 7915  },
  { rank: 2,  nation: "Austria",         points: 7109  },
  { rank: 3,  nation: "Mexico",          points: 6871  },
  { rank: 4,  nation: "Italy",           points: 6248  },
  { rank: 5,  nation: "France",          points: 6121  },
  { rank: 6,  nation: "Switzerland",     points: 5949  },
  { rank: 7,  nation: "Japan",           points: 5869  },
  { rank: 8,  nation: "Australia",       points: 5703  },
  { rank: 9,  nation: "Israel",          points: 5667  },
  { rank: 10, nation: "Canada",          points: 5628  },
  { rank: 11, nation: "Germany",         points: 5426  },
  { rank: 12, nation: "Great Britain",   points: 5230  },
  { rank: 13, nation: "Panama",          points: 5180  },
  { rank: 14, nation: "Denmark",         points: 4954  },
  { rank: 15, nation: "New Zealand",     points: 4860  },
  { rank: 16, nation: "Spain",           points: 4612  },
  { rank: 17, nation: "Brazil",          points: 4516  },
  { rank: 18, nation: "Sweden",          points: 4510  },
  { rank: 19, nation: "Ireland",         points: 4413  },
  { rank: 20, nation: "Ukraine",         points: 4374  },
  { rank: 21, nation: "Finland",         points: 4305  },
  { rank: 22, nation: "Czechia",         points: 4196  },
  { rank: 23, nation: "Argentina",       points: 4089  },
  { rank: 24, nation: "Kuwait",          points: 3973  },
  { rank: 25, nation: "Chile",           points: 3900  },
  { rank: 26, nation: "Poland",          points: 3802  },
  { rank: 27, nation: "Singapore",       points: 3685  },
  { rank: 28, nation: "Korea",           points: 3590  },
  { rank: 29, nation: "Thailand",        points: 3500  },
  { rank: 30, nation: "Georgia",         points: 3336  },
  { rank: 31, nation: "Cameroon",        points: 3133  },
  { rank: 32, nation: "Nigeria",         points: 2980  },
  { rank: 33, nation: "American Samoa",  points: 2900  },
  { rank: 34, nation: "China",           points: 2800  },
  { rank: 35, nation: "Egypt",           points: 2620  },
  { rank: 36, nation: "Indonesia",       points: 2590  },
  { rank: 37, nation: "Tunisia",         points: 2540  },
  { rank: 38, nation: "Slovenia",        points: 2463  },
  { rank: 39, nation: "Netherlands",     points: 2413  },
  { rank: 40, nation: "Philippines",     points: 2396  },
  { rank: 41, nation: "Hungary",         points: 2200  },
  { rank: 42, nation: "Guatemala",       points: 2150  },
  { rank: 42, nation: "Croatia",         points: 2150  },
  { rank: 42, nation: "Hong Kong, China",points: 2150  },
  { rank: 45, nation: "Portugal",        points: 2138  },
  { rank: 46, nation: "Belgium",         points: 2073  },
  { rank: 47, nation: "Slovakia",        points: 2072  },
  { rank: 48, nation: "Morocco",         points: 2070  },
  { rank: 49, nation: "Colombia",        points: 2067  },
  { rank: 50, nation: "South Africa",    points: 2050  },
  { rank: 51, nation: "Norway",          points: 1975  },
  { rank: 52, nation: "Jamaica",         points: 1967  },
  { rank: 53, nation: "Jordan",          points: 1925  },
  { rank: 54, nation: "El Salvador",     points: 1900  },
  { rank: 55, nation: "Senegal",         points: 1850  },
  { rank: 56, nation: "India",           points: 1794  },
  { rank: 57, nation: "Uganda",          points: 1600  },
  { rank: 58, nation: "Serbia",          points: 986   },
  { rank: 59, nation: "Malaysia",        points: 100   },
];

// Populate with NCFFA / NIRSA data — leave empty until data is sourced
export const COLLEGE_RANKINGS: CollegeTeamRanking[] = [];
